promtail:
  serviceAccount:
    create: false
    name: "loki-promtail"
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: gcplog
          gcplog:
            project_id: "psychic-sensor-230117"
            subscription: "psychic-sensor-230117-log-subscription"
            use_incoming_timestamp: false # default rewrite timestamps.
            # labels:
              # job: "gcplog"
          relabel_configs:
            - source_labels: ["__gcp_resource_labels_job_name"]
              target_label: "job_name"
